apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: plaid-category-collector
      context: .
      jib: {
        args: [-Pdocker-image]
      }
deploy:
  kubectl:
    flags:
      global:
        - --namespace=dope
    manifests:
      - ./kubernetes-manifests/**.yaml