apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: plaid-transaction-enricher
      context: .
      jib: {

      }
deploy:
  kubectl:
    flags:
      global:
        - --namespace=dope
    manifests:
      - ./kubernetes-manifests/**.yaml