eureka:
  client:
    enabled: false

logging:
  level:
    root: info

backbase:
#  security:
#    public:
#      paths:
#        - /links
#        - /api/plaid-service/links

  plaid:
    client-id:
    secret:
    env: sandbox
    country-codes:
      - NL
      - CA
    products:
      - auth

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false

