eureka:
  client:
    enabled: false

logging:
  level:
    root: info


spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-persistence.yaml
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id:-client
            client-secret:-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri:
  mvc:
    log-request-details: true

backbase:
  security:
    public:
      paths:
        - /webhook/*
  stream:
    dbs:
      user-manager-base-url:
      access-control-base-url:
      arrangement-manager-base-url:
      transaction-manager-base-url:
      limits-manager-base-url:
  plaid:
    client-name: "Backbase"
    client-id:
    secret:
    env: sandbox
    webhook-base-url:
    country-codes:
      - NL
      - CA
    products:
      - auth
      - transactions
    transactions:
      transactionTypeGroupMap:
        online: "Payment"
        in_store: "Payment"
        other: "Fees"
      transactionTypeMap:
        online: "Credit/Debit Card"
        in_store: "Credit/Debit Card"
        other: "Fee"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false
