eureka:
  client:
    enabled: false

logging:
  level:
    root: info

spring:
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id:-client
            client-secret:-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri:

backbase:
  stream:
    dbs:
      user-manager-base-url:
      access-control-base-url:
      arrangement-manager-base-url:
      transaction-manager-base-url:
      limits-manager-base-url:
  #  security:
  #    public:
  #      paths:
  #        - /links
  #        - /api/plaid-service/links

  plaid:
    client-name: "Backbase"
    client-id:
    secret:
    env: sandbox
    country-codes:
      - NL
      - CA
    products:
      - auth
      - transactions
    transactions:
      transactionTypeGroupMap:
        online: "Payment"
        in_store: "Payment"
        other: "Fees"
      transactionTypeMap:
        online: "Credit/Debit Card"
        in_store: "Credit/Debit Card"
        other: "Fee"




management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false
