eureka:
  client:
    enabled: false

logging:
  level:
    root: debug

backbase:
  security:
    public:
      paths:
        - /links
        - /api/plaid-service/links

  plaid:
    client-id:
    secret:
    env: sandbox
    country-codes:
      - NL
      - CA
    products:
      - auth


