eureka:
  client:
    enabled: false

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-persistence.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: ${DBS_CLIENT_ID}
            client-secret: ${DBS_CLIENT_SECRET}
            client-authentication-method: post
        provider:
          dbs:
            token-uri: ${DBS_TOKEN_URI}

backbase:
  security:
    public:
      paths:
        - /categories
        - /transactions/enrich
        - /service-api/v2/*
        - /webhook/*
        - /webhook/*/refresh-transactions
    csrf:
      enabled: false
  stream:
    dbs:
      user-manager-base-url: ${USER_MANAGER_BASE_URL}
      access-control-base-url: ${ACCESS_CONTROL_BASE_URL}
      arrangement-manager-base-url: ${ARRANGEMENT_MANAGER_BASE_URL}
      transaction-manager-base-url: ${TRANSCATION_MANGER_BASE_URL}
      limits-manager-base-url: ${LIMITS_MANAGER_BASE_URL}

  plaid:
    client-name: "Backbase"
    client-id: ${PLAID_CLIENT_ID}
    secret: ${PLAID_CLIENT_SECRET}
    env: sandbox
    webhook-base-url: ${PLAID_WEBHOOK_BASE}
    default-reference-job-role-names:
      - "Retail User - EU"
      - "Retail User - USA"
    country-codes:
      - US
      - NL
    products:
      - auth
      - transactions
    accounts:
      accountTypeMapping:
        depository:
          checking: "current-account"
          savings: "savings-account"
        credit:
          "credit-card": "credit-card"
        loan:
          loan: "loan"


    transactions:
      # Payment,Withdrawal,Loans,Fees
      transactionTypeGroupMap:
        online: "Withdrawal"
        store: "Withdrawal"
        "in store": "Withdrawal"
        other: "Fees"
      # ATM, ACH, Bill Payment, Cash, Cheques, Credit/Debit Card, Check, Deposit, Fee, POS, Withdrawal
      transactionTypeMap:
        online: "Credit/Debit Card"
        store: "Credit/Debit Card"
        other: "Fee"
      description-parser-for-institution:
        ins_120509:
          counter-party-name:
            - .+?(?=Pasvolgnr:)
          counter-party-bban:
            - (?<=IBAN:\s)(.*?)[?:\s]
          description:
            - .+?(?=Pasvolgnr:)
            - .*
          cardId:
            - (?<=Pasvolgnr:\s)(.*?)[?:\s]
          reference:
            - (?<=Transactie:\s)(.*?)[?:\s]
          bookingDate:
            - (?<=Valutadatum:\s)(.*?)[?:\s]
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false

stream:
  start:
    title: "Stream Plaid"
    subTitle: Stream <strong class="highlight">Plaid</strong>
    header: Stream <strong class="highlight">Plaid</strong>
    description: "Seamlessly integrate with Plaid with Stream Plaid. This service is provides an implementation for Account Integration Services, Transactions and Payments"
    footer: "Plaid"
    defaultAction:
      name: Swagger
      href: swagger-ui.html
    navbarLinks:
      - name: Communtiy
        href: https://community.backbase.com