eureka:
  client:
    enabled: false

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url:
    username:
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-persistence.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id:-client
            client-secret:-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri:

backbase:
  security:
    public:
      paths:
        - /webhook/*
        - /webhook/*/refresh-transactions
    csrf:
      enabled: false
  stream:
    dbs:
      user-manager-base-url:
      access-control-base-url:
      arrangement-manager-base-url:
      transaction-manager-base-url:
      limits-manager-base-url:

  plaid:
    client-name: "Backbase"
    client-id:
    secret:
    env: sandbox
    webhook-base-url:
    default-reference-job-role-names:
      - "Retail User - EU"
    country-codes:
      - NL
      - CA
    products:
      - auth
      - transactions
    transactions:
      # Payment,Withdrawal,Loans,Fees
      transactionTypeGroupMap:
        online: "Withdrawal"
        store: "Withdrawal"
        "in store": "Withdrawal"
        other: "Fees"
      # ATM, ACH, Bill Payment, Cash, Cheques, Credit/Debit Card, Check, Deposit, Fee, POS, Withdrawal
      transactionTypeMap:
        online: "Credit/Debit Card"
        store: "Credit/Debit Card"
        other: "Fee"
      description-parser-for-institution:
        ins_120509:
          counter-party-name:
            - .+?(?=Pasvolgnr:)
          counter-party-bban:
            - (?<=IBAN:\s)(.*?)[?:\s]
          description:
            - .+?(?=Pasvolgnr:)
            - .*
          cardId:
            - (?<=Pasvolgnr:\s)(.*?)[?:\s]
          reference:
            - (?<=Transactie:\s)(.*?)[?:\s]
          bookingDate:
            - (?<=Valutadatum:\s)(.*?)[?:\s]
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false
