apiVersion: v1
data:
  plaid-client-name: "Backbase"
  plaid-env: sandbox
  webhook-base-url: https://gateway.proto.backbasecloud.com/api/plaid-service

kind: ConfigMap
metadata:
  name:  plaid-client-credentials
  namespace: dope