apiVersion: apps/v1
kind: Deployment
metadata:
  name: plaid-service
  labels:
    app: plaid-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plaid-service
      tier: backend
  template:
    metadata:
      labels:
        app: plaid-service
        tier: backend
    spec:
      containers:
        - name: plaid-service
          image: plaid-service
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: spring.zipkin.baseUrl
              valueFrom:
                configMapKeyRef:
                  key:
                  name: zipkin-config
            - name: SIG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key:
                  name: backbase-env-dope-jwt
            - name: USERCTX_KEY
              valueFrom:
                secretKeyRef:
                  key:
                  name: backbase-env-dope-jwt
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_RIBBON_MODE
              value: SERVICE
            - name: SPRING_CLOUD_STREAM_DEFAULT_BINDER
              value: "activemq"
            - name: SPRING_DATASOURCE_VALIDATIONQUERY
              value: SELECT 1
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration
            - name: spring.cloud.loadbalancer.ribbon.enabled
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://proto.cdem7uw0kede.eu-central-1.rds.amazonaws.com/plaid?useSSL=false
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.jdbc.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: backbase
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key:
                  name: backbase-env-mysql
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"
