apiVersion: v1
data:
  spring-activemq-brokerurl: ssl://b-9d1ef816-ccb2-4ec5-a4e8-3e2c2c9bbda0-1.mq.eu-central-1.amazonaws.com:61617
  spring-activemq-user: admin
  spring-datasource-categories-url: jdbc:mysql://proto.cdem7uw0kede.eu-central-1.rds.amazonaws.com/dbs_categories?useSSL=false
  spring-datasource-categories-driverclass: com.mysql.jdbc.Driver
  spring-datasource-categories-username: backbase
  plaid-client-id: "***REMOVED***"
  plaid-client-secret: "***REMOVED***"


kind: ConfigMap
metadata:
  name: category-collector-database-configurations
  namespace: dope
