apiVersion: v1
kind: Service
metadata:
  name: plaid-category-collector
  labels:
    app: plaid-category-collector
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: plaid-category-collector
    tier: backend
  ports:
    - port: 8080
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-category-collector
  labels:
    app: plaid-category-collector
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: plaid-category-collector
    tier: backend
  ports:
    - port: 8080
      targetPort: http
