openapi: "3.0.0"
info:
  version: 1.0.0
  title: Backbase Plaid Integration Service
  license:
    name: Backbase
servers:
  - url:
paths:
  /links/request_plaid_link:
    post:
      summary: Request plaid link
      operationId: requestPlaidLink
      tags:
        - plaid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaidLinkRequest'
      responses:
        '200':
          description: Plaid Link to use in when invoking the Plaid Link UI
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaidLinkResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /links/set_access_token:
    post:
      summary: Set Public Access Token
      operationId: setPublicAccessToken
      tags:
        - plaid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetAccessTokenRequest'
      responses:
        '201':
          description: A paged array of pets
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    PlaidLinkRequest:
      type: object
      properties:
        language:
          type: string
        name:
          type: string
    PublicTokenRequest:
      type: object
      properties:
        public-token:
          type: string
      required:
        - public-token
    PlaidLinkResponse:
      type: object
      properties:
        token:
          type: string
    SetAccessTokenRequest:
      properties:
        public_token:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'

    Metadata:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/PlaidAccount'
        account_id:
          type: string
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/PlaidAccount'
        institution:
          $ref: '#/components/schemas/PlaidInstitution'

    PlaidAccount:
      type: object
      properties:
        id:
          type: string
        mask:
          type: string
        name:
          type: string
        subtype:
          type: string
        type:
          type: string
    PlaidInstitution:
      type: object
      properties:
        institution_id:
          type: string
        name:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string