apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: "plaid-service"
      context: .
      jib: {
        args: [ "-Pdocker-image,no-scs" ]
      }
deploy:
  kubectl:
    flags:
      global:
        - --namespace=dope
    manifests:
      - ./kubernetes-manifests/**.yaml